### ISSUE TITLE
New code stopped certain servo functions

### ISSUE THREAD

**Issue by tc0nn** [sunfounder/Sunfounder_Smart_Video_Car_Kit_for_RaspberryPi#10]
I built and ran this kit earlier this year. I just pulled the latest code from github and now my camera wont move left/right... Was there something more to it than just git pull origin master ?

**Comment by tc0nn** [comment]
Never mind. A reboot of the PI seems to have resolved it.

**Comment by sunfounder** [comment]
Good to know that. Please feel free to contact us if you have any questions.
