### ISSUE TITLE
git clone on a pi requires authentication

### ISSUE THREAD

**Issue by neilyoung** [sunfounder/Sunfounder_Smart_Video_Car_Kit_for_RaspberryPi#29]
I'm trying to clone the Sunfounder Kit on a headless PI (connected via SSH from a Mac).

`pi@raspberrypi:~ $ git clone https://github.com/sunfounder/Sunfounder_Smart_Video_Car_ Kit_for_RaspberryPi`

I'm getting asked for a username and password for the repo, which I of course don't have...

What to do?

**Comment by aliasbox** [comment]
on a YouTube tutorial I remember hearing psswd is "pi" and/or "raspberry" or "raspbian" (don't remember which video)

**Comment by Coder2444** [comment]
which is which. What is the username and what is the password

**Comment by rfisher001** [comment]
When you copy and paste from the PDF it puts a space in there. Take the space out and then it won't ask for the password.
