### ISSUE TITLE
Not a BUG: Do you have some user forum? Or I should post my questions here??

### ISSUE THREAD

**Issue by arm2arm** [sunfounder/Sunfounder_Smart_Video_Car_Kit_for_RaspberryPi#6]
Do you have some user forum? Or I should post my questions here??

**Comment by sunfounder** [comment]
If the question is software related, I recommend you to post your question here, If it's hardware related you can post it to our forum: https://www.sunfounder.com/forum. you can also write us an email: support@sunfounder.com

**Comment by arm2arm** [comment]
Nice!
